package model.constants;

import java.util.HashSet;

public class ExceptionTexts {

    //MOBILE
    public static final HashSet<String> mobileErrors = getMobileErrors();
    //registration
    public static final String registrationNoModelException = "phone.registration.model.empty";
    public static final String registrationNoDeviceIDException = "phone.registration.deviceID.empty";
    public static final String registrationDeviceIDNotUniqueException = "phone.registration.deviceID.notUnique";
    public static final String registrationNoLanguageException = "phone.registration.language.empty";
    public static final String registrationIllegalLanguageException = "phone.registration.language.illegal";
    public static final String registrationNoDeviseTokenException = "phone.registration.deviceToken.empty";
    public static final String registrationNoPlatformTypeException = "phone.registration.mobilePlatform.empty";
    public static final String registrationIllegalMobilePlatformException = "phone.registration.mobilePlatform.illegal";
    public static final String allMenusUserIDEmptyException = "phone.getAllMenus.UserID.empty";
    public static final String allMenusUserIDIncorrectException = "phone.getAllMenus.UserID.Incorrect";
    public static final String allMenusUserNotExistException = "phone.getAllMenus.UserID.NotExist";
    public static final String getMenuUserIDEmptyException = "phone.getMenu.UserID.empty";
    public static final String getMenuUserIDIncorrectException = "phone.getMenu.UserID.Incorrect";
    public static final String getMenuUserNotExistException = "phone.getMenu.UserID.NotExist";
    public static final String getMenuMenuIDEmptyException = "phone.getMenu.MenuID.empty";
    public static final String getMenuMenuIDIncorrectException = "phone.getMenu.MenuID.Incorrect";
    public static final String allCardsUserIDEmptyException = "phone.getAllCards.UserID.empty";
    public static final String allCardsUserIDIncorrectException = "phone.getAllCards.UserID.Incorrect";
    public static final String allCardsUserNotExistException = "phone.getAllCards.UserID.NotExist";
    public static final String allCardsLimitIncorrectException = "phone.getAllCards.Limit.Incorrect";
    public static final String allCardsLimitTooBigException = "phone.getAllCards.Limit.TooBig";
    public static final String allCardsLimitEmptyException = "phone.getAllCards.Limit.Empty";
    public static final String allCardsOffsetIncorrectException = "phone.getAllCards.Offset.Incorrect";
    public static final String allCardsOffsetEmptyException = "phone.getAllCards.Offset.Empty";
    public static final String weatherUserIDEmptyException = "phone.weather.UserID.empty";
    public static final String weatherUserIDIncorrectException = "phone.weather.UserID.Incorrect";
    public static final String weatherUserNotExistException = "phone.weather.UserID.NotExist";
    public static final String getViewImagesUserIDEmptyException = "phone.getViewImages.UserID.Empty";
    public static final String getViewImagesUserIDIncorrectException = "phone.getViewImages.UserID.Incorrect";
    public static final String getViewImagesUserNotExistException = "phone.getViewImages.UserID.NotExist";
    public static final String restoreUserDeviceIDEmptyException = "phone.restoreUser.DeviceID.Empty";
    public static final String restoreUserDeviceNotFoundException = "phone.restoreUser.Device.NotFound";
    public static final String getAllCardParameterTypesUserIDEmptyException = "phone.getAllCardParameterTypes.UserID.Empty";
    public static final String getAllCardParameterTypesIncorrectException = "phone.getAllCardParameterTypes.UserID.Incorrect";
    public static final String getAllCardParameterTypesUserNotExistException = "phone.getAllCardParameterTypes.UserID.NotExist";
    public static final String allTagsUserIDEmptyException = "phone.allTags.UserID.Empty";
    public static final String allTagsUserIDIncorrectException = "phone.allTags.UserID.Incorrect";
    public static final String allTagsUserNotExistException = "phone.allTags.UserID.NotExist";
    public static final String getAllDishCategoriesUserIDEmptyException = "phone.getAllDishCategories.UserID.Empty";
    public static final String getAllDishCategoriesIncorrectException = "phone.getAllDishCategories.UserID.Incorrect";
    public static final String getAllDishCategoriesUserNotExistException = "phone.getAllDishCategories.UserID.NotExist";
    public static final String getAllDishTagsUserIDEmptyException = "phone.getAllDishTags.UserID.Empty";
    public static final String getAllDishTagsIncorrectException = "phone.getAllDishTags.UserID.Incorrect";
    public static final String getAllDishTagsUserNotExistException = "phone.getAllDishTags.UserID.NotExist";
    public static final String allPricesLimitTooBigException = "phone.allPrices.Limit.TooBig";
    public static final String allPricesLimitIncorrectException = "phone.allPrices.Limit.Incorrect";
    public static final String allPricesLimitEmptyException = "phone.allPrices.Offset.Empty";
    public static final String allPricesOffsetIncorrectException = "phone.allPrices.Offset.Incorrect";
    public static final String exchangeRatesUserIDEmptyException = "phone.exchangeRates.UserID.Empty";
    public static final String exchangeRatesUserIDIncorrectException = "phone.exchangeRates.UserID.Incorrect";
    public static final String cardByListCardListEmptyException = "phone.cardbylist.CardList.Empty";
    public static final String cardByListUserIDIncorrectException = "phone.cardbylist.UserID.Incorrect";
    public static final String cardByListBodyEmptyException = "phone.cardbylist.Body.Empty";
    public static final String cardRegistrationUserIDIncorrectException = "phone.cardregistration.UserID.Incorrect";
    public static final String cardRegistrationBodyEmptyException = "phone.cardregistration.Body.Empty";
    public static final String cardRegistrationCardListEmptyException = "phone.cardregistration.CardList.Empty";
    public static final String pricesRegistrationUserIDIncorrectException = "phone.pricesregistration.UserID.Incorrect";
    public static final String pricesRegistrationBodyEmptyException = "phone.pricesregistration.Body.Empty";
    public static final String pricesRegistrationPriceListEmptyException = "phone.pricesregistration.PricesList.Empty";
    public static final String cardByListPriceListEmptyException = "phone.cardByListPrice.PricesList.Empty";


    private static HashSet<String> getMobileErrors() {
        HashSet<String> mobileErrors = new HashSet<>();
        mobileErrors.add(registrationNoModelException);
        mobileErrors.add(registrationNoDeviceIDException);
        mobileErrors.add(registrationDeviceIDNotUniqueException);
        mobileErrors.add(registrationNoLanguageException);
        mobileErrors.add(registrationIllegalLanguageException);
        mobileErrors.add(allMenusUserIDEmptyException);
        mobileErrors.add(allMenusUserIDIncorrectException);
        mobileErrors.add(allMenusUserNotExistException);
        mobileErrors.add(getMenuUserIDEmptyException);
        mobileErrors.add(getMenuUserIDIncorrectException);
        mobileErrors.add(getMenuUserNotExistException);
        mobileErrors.add(getMenuMenuIDEmptyException);
        mobileErrors.add(getMenuMenuIDIncorrectException);
        mobileErrors.add(allCardsUserIDEmptyException);
        mobileErrors.add(allCardsUserIDIncorrectException);
        mobileErrors.add(allCardsUserNotExistException);
        mobileErrors.add(allCardsLimitIncorrectException);
        mobileErrors.add(allCardsLimitTooBigException);
        mobileErrors.add(allCardsLimitEmptyException);
        mobileErrors.add(allCardsOffsetIncorrectException);
        mobileErrors.add(allCardsOffsetEmptyException);
        mobileErrors.add(weatherUserIDEmptyException);
        mobileErrors.add(weatherUserIDIncorrectException);
        mobileErrors.add(weatherUserNotExistException);
        mobileErrors.add(getViewImagesUserIDEmptyException);
        mobileErrors.add(getViewImagesUserIDIncorrectException);
        mobileErrors.add(getViewImagesUserNotExistException);
        mobileErrors.add(restoreUserDeviceIDEmptyException);
        mobileErrors.add(restoreUserDeviceNotFoundException);
        mobileErrors.add(getAllCardParameterTypesUserIDEmptyException);
        mobileErrors.add(getAllCardParameterTypesIncorrectException);
        mobileErrors.add(getAllCardParameterTypesUserNotExistException);
        mobileErrors.add(allTagsUserIDEmptyException);
        mobileErrors.add(allTagsUserIDIncorrectException);
        mobileErrors.add(allTagsUserNotExistException);
        mobileErrors.add(getAllDishCategoriesUserIDEmptyException);
        mobileErrors.add(getAllDishCategoriesIncorrectException);
        mobileErrors.add(getAllDishCategoriesUserNotExistException);
        mobileErrors.add(getAllDishTagsUserIDEmptyException);
        mobileErrors.add(getAllDishTagsIncorrectException);
        mobileErrors.add(getAllDishTagsUserNotExistException);
        mobileErrors.add(allPricesLimitTooBigException);
        mobileErrors.add(allPricesLimitIncorrectException);
        mobileErrors.add(allPricesLimitEmptyException);
        mobileErrors.add(allPricesOffsetIncorrectException);
        mobileErrors.add(exchangeRatesUserIDEmptyException);
        mobileErrors.add(exchangeRatesUserIDIncorrectException);
        mobileErrors.add(cardByListCardListEmptyException);
        mobileErrors.add(cardByListUserIDIncorrectException);
        mobileErrors.add(cardByListBodyEmptyException);
        mobileErrors.add(cardRegistrationUserIDIncorrectException);
        mobileErrors.add(cardRegistrationBodyEmptyException);
        mobileErrors.add(cardRegistrationCardListEmptyException);
        return mobileErrors;
    }
}
